"""Convenience script to load a compiled program and run it on the pipeline model.

Usage:
    python -m pipeline.run_program --program programa.txt [--max-cycles N]

The program file must contain one 32-bit instruction per line in hexadecimal
format (for example, generated by the ISA assembler with ``--format hex``).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable, List

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from pipeline import Pipeline


def _parse_hex_lines(lines: Iterable[str]) -> List[int]:
    instructions: List[int] = []
    for raw in lines:
        stripped = raw.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue
        try:
            instructions.append(int(stripped, 16))
        except ValueError as exc:
            raise ValueError(f"Línea inválida en programa: '{raw.strip()}'") from exc
    if not instructions:
        raise ValueError("El programa no contiene instrucciones válidas")
    return instructions


def load_program(path: Path) -> List[int]:
    if not path.exists():
        raise FileNotFoundError(f"No se encontró el archivo de programa: {path}")
    return _parse_hex_lines(path.read_text().splitlines())


def main() -> None:
    parser = argparse.ArgumentParser(description="Ejecuta un programa compilado en el pipeline")
    parser.add_argument(
        "--program",
        "-p",
        type=Path,
        default=Path("programa.txt"),
        help="Ruta al archivo con instrucciones en hexadecimal (por defecto: programa.txt)",
    )
    parser.add_argument(
        "--max-cycles",
        type=int,
        default=None,
        help="Número máximo de ciclos a ejecutar (por defecto: todos los disponibles)",
    )
    args = parser.parse_args()

    instructions = load_program(args.program)
    print(f" Programa cargado ({len(instructions)} instrucciones) desde {args.program}")

    pipeline = Pipeline(instructions)
    pipeline.run(max_cycles=args.max_cycles)


if __name__ == "__main__":
    main()
